inherit_from: configs/base_params.yaml

transform:
  size: [256,256]

dataset:
  name: apple2orange
  path: ./datasets/apple2orange
  direction: AtoB
  A_channel: 3
  B_channel: 3
  save_dir: ./checkpoints/apple2orange