inherit_from: configs/base_params.yaml

transform:
  size: [128,128]

dataset:
  name: cityscapes
  path: ./datasets/cityscapes/fcn
  direction: BtoA
  A_channel: 3
  B_channel: 3
  save_dir: ./checkpoints/cityscapes_Batch_0.1_MSE