inherit_from: configs/base_params.yaml

transform:
  size: [128,128]

dataset:
  name: cityscapes
  path: ./datasets/cityscapes
  direction: BtoA
  A_channel: 3
  B_channel: 3
  save_dir: ./checkpoints/cityscapes

training_args:
  lambda_idt: 0