inherit_from: configs/base_params.yaml

transform:
  size: [256,256]

dataset:
  name: facades
  path: ./datasets/facades
  direction: AtoB
  A_channel: 3
  B_channel: 3
  save_dir: ./checkpoints/facades