inherit_from: configs/base_params.yaml

transform:
  size: [256,256]

dataset:
  name: horse2zebra
  path: ./datasets/horse2zebra
  direction: BtoA
  A_channel: 3
  B_channel: 3
  save_dir: ./checkpoints/horse2zebra