inherit_from: configs/base_params.yaml

transform:
  size: [256,256]

dataset:
  name: iphone2dslr_flower
  path: ./datasets/iphone2dslr_flower
  direction: AtoB
  A_channel: 3
  B_channel: 3
  save_dir: ./checkpoints/iphone2dslr_flower