inherit_from: configs/base_params.yaml

transform:
  size: [512,512]

dataset:
  name: monet2photo
  path: ./datasets/monet2photo
  direction: AtoB
  A_channel: 3
  B_channel: 3
  save_dir: ./checkpoints/monet2photo