inherit_from: configs/base_params.yaml

transform:
  size: [256,256]

dataset:
  name: monet2photo
  path: ./datasets/monet2photo
  direction: BtoA
  A_channel: 3
  B_channel: 3
  save_dir: ./checkpoints/monet2photo