inherit_from: configs/base_params.yaml

transform:
  size: [256,256]

dataset:
  name: summer2winter_yosemite
  path: ./datasets/summer2winter_yosemite
  direction: BtoA
  A_channel: 3
  B_channel: 3
  save_dir: ./checkpoints/summer2winter_yosemite