inherit_from: configs/base_params.yaml

transform:
  size: [256,256]

dataset:
  name: ukiyoe2photo
  path: ./datasets/ukiyoe2photo
  direction: BtoA
  A_channel: 3
  B_channel: 3
  save_dir: ./checkpoints/ukiyoe2photo