inherit_from: configs/base_params.yaml

transform:
  size: [256,256]

dataset:
  name: vangogh2photo
  path: ./datasets/vangogh2photo
  direction: BtoA
  A_channel: 3
  B_channel: 3
  save_dir: ./checkpoints/vangogh2photo